"""Pydantic schemas and enums for orchestrating AutoAD pipeline sessions."""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class PipelineStage(str, Enum):
    """Enumerated stages emitted while the agent pipeline is executing."""

    QUEUED = "queued"
    PREPARING = "preparing"
    RETRIEVAL = "retrieval"
    IDEA_GENERATION = "idea_generation"
    NOVELTY_CHECK = "novelty_check"
    EXECUTION = "execution"
    COMPLETE = "complete"
    FAILED = "failed"

class SessionCreateRequest(BaseModel):
    """Inbound payload describing how to launch an AutoAD session."""

    project_slug: str = Field(..., description="Previously scaffolded project slug to operate on.")
    model: str = Field(
        "gemini-2.5-flash-lite",
        description="LLM model identifier used for idea generation, RAG, and novelty checks.",
    )
    code_model: str = Field(
        "flash",
        description="Model identifier passed to the aider code editor when implementing experiments.",
    )
    parallel: int = Field(
        0,
        ge=0,
        le=8,
        description="Number of parallel experiment executions to spawn (0 for sequential).",
    )
    num_ideas: int = Field(
        10,
        ge=1,
        le=50,
        description="Maximum number of candidate ideas to request from the LLM.",
    )
    skip_idea_generation: bool = Field(
        False,
        description="Reuse cached ideas instead of generating new ones when set to True.",
    )
    skip_novelty_check: bool = Field(
        False,
        description="Bypass the novelty filter and treat all ideas as novel when True.",
    )
    check_similarity: bool = Field(
        False,
        description="Enable embedding-based similarity filtering to enforce idea independence.",
    )
    embedding_model: str = Field(
        "sentence-transformers/all-roberta-large-v1",
        description="Embedding model used when similarity checks are enabled.",
    )
    use_rag: Optional[bool] = Field(
        None,
        description="Override the project's RAG preference for this run (None keeps project default).",
    )
    topic_override: Optional[str] = Field(
        None,
        description="Override the topic stored in the project configuration for this run.",
    )
    round: int = Field(
        0,
        ge=0,
        description="Iteration round number; higher values reuse artifacts from previous rounds.",
    )


class SessionCreateResponse(BaseModel):
    """Returned after a new session has been enqueued for execution."""

    session_id: str = Field(..., description="Unique identifier for tracking this pipeline run.")


class SessionEvent(BaseModel):
    """Single status breadcrumb emitted while the pipeline progresses."""

    timestamp: datetime = Field(..., description="UTC timestamp when the event was recorded.")
    stage: PipelineStage = Field(..., description="Pipeline stage that produced this event.")
    message: str = Field(..., description="Human-readable status update for the frontend.")
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Structured payload with contextual details for advanced UIs.",
    )


class SessionStatus(BaseModel):
    """Detailed session view consumed by polling clients."""

    session_id: str
    project_slug: str
    stage: PipelineStage
    started_at: datetime
    updated_at: datetime
    completed: bool = False
    failed: bool = False
    error: Optional[str] = None
    events: List[SessionEvent] = Field(default_factory=list)
    result_paths: List[str] = Field(
        default_factory=list,
        description="Collection of result directories generated by successful ideas.",
    )


class SessionListItem(BaseModel):
    """Lightweight listing row for dashboards showing pipeline history."""

    session_id: str
    project_slug: str
    stage: PipelineStage
    started_at: datetime
    updated_at: datetime
    completed: bool
    failed: bool